[versions]
agp = "8.9.1"
kotlin = "2.1.20"
# https://github.com/google/ksp/releases
ksp = "2.1.20-1.0.31"
aboutlibraries = "11.6.3"

composeBom = "2025.03.01"
material = "1.12.0"
androidxCore = "1.15.0"
androidxCompose = "1.10.1"
androidxLifecycle = "2.8.7"
androidxCompat = "1.7.0"
androidxAnimation = "1.7.8"
androidxSplashScreen = "1.0.1"
androidxBrowser = "1.8.0"
androidxFuture = "1.2.0"
androidxRoom = "2.6.1"

aboutlibrariesDependencies = "11.6.3"
lottie = "6.6.4"
koin = "4.0.3"
coil = "2.7.0"
retrofit = "2.11.0"
moshi = "1.15.2"
mmkv = "2.1.0"
composePreference = "1.1.1"
media3Exoplayer = "1.6.0"

[libraries]
gradle = { group = "com.android.tools.build", name = "gradle", version.ref = "agp" }

androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidxCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "androidxLifecycle" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "androidxCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-material3-window-size = { group = "androidx.compose.material3", name = "material3-window-size-class" }
androidx-material-icon = { group = "androidx.compose.material", name = "material-icons-core" }
androidx-material-icon-extended = { group = "androidx.compose.material", name = "material-icons-extended" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidxCompat" }
androidx-animation = { group = "androidx.compose.animation", name = "animation", version.ref = "androidxAnimation" }
androidx-foundation = { module = "androidx.compose.foundation:foundation" }
androidx-splashscreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "androidxSplashScreen" }
androidx-browser = { group = "androidx.browser", name = "browser", version.ref = "androidxBrowser" }
androidx-concurrent-futures = { group = "androidx.concurrent", name = "concurrent-futures", version.ref = "androidxFuture" }
androidx-room = { group = "androidx.room", name = "room-runtime", version.ref = "androidxRoom" }
androidx-room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "androidxRoom" }
androidx-room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "androidxRoom" }

lottie = { group = "com.airbnb.android", name = "lottie-compose", version.ref = "lottie" }

koin = { group = "io.insert-koin", name = "koin-android", version.ref = "koin" }
koin-compose = { group = "io.insert-koin", name = "koin-androidx-compose", version.ref = "koin" }

coil-compose = { group = "io.coil-kt", name = "coil-compose", version.ref = "coil" }
coil-gif = { group = "io.coil-kt", name = "coil-gif", version.ref = "coil" }

retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
retrofit-moshi = { group = "com.squareup.retrofit2", name = "converter-moshi", version.ref = "retrofit" }

moshi = { group = "com.squareup.moshi", name = "moshi", version.ref = "moshi" }
moshi-kotlin = { group = "com.squareup.moshi", name = "moshi-kotlin", version.ref = "moshi" }

mmkv = { group = "com.tencent", name = "mmkv-static", version.ref = "mmkv" }

compose-preference = { group = "me.zhanghai.compose.preference", name = "library", version.ref = "composePreference" }

media3-exoplayer = { group = "androidx.media3", name = "media3-exoplayer", version.ref = "media3Exoplayer" }
media3-exoplayer-dash = { group = "androidx.media3", name = "media3-exoplayer-dash", version.ref = "media3Exoplayer" }
media3-ui = { group = "androidx.media3", name = "media3-ui", version.ref = "media3Exoplayer" }

aboutlibraries = { group = "com.mikepenz", name = "aboutlibraries-core", version.ref = "aboutlibrariesDependencies" }
aboutlibraries-compose = { group = "com.mikepenz", name = "aboutlibraries-compose-m3", version.ref = "aboutlibrariesDependencies" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
about-libraries = { id = "com.mikepenz.aboutlibraries.plugin", version.ref = "aboutlibraries" }
