name: "Build Commit"
on:
  workflow_dispatch:
env:
  OUTPUT_DIR: "app/release"
  SIGN_KEY_ALIAS: ${{ secrets.SIGN_KEY_ALIAS }}
  SIGN_KEY_STORE_PASSWORD: ${{ secrets.SIGN_KEY_STORE_PASSWORD }}
  SIGN_KEY_PASSWORD: ${{ secrets.SIGN_KEY_PASSWORD }}
  SIGN_KEY_STORE_FILE: "/tmp/key.jks"
jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    steps:
      - uses: actions/checkout@v4
      - name: 设置JDK
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'
      - name: 设置Android SDK
        uses: android-actions/setup-android@v3
      - name: 解密签名
        run: |
          echo ${{ secrets.SIGN_KEY_BASE64 }} | base64 --decode > /tmp/key.jks
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: 构建 APK
        run: ./gradlew bundleRelease
      - name: 安装工具
        run: |
          sudo apt-get install wget -y
      - name: 解析版本号
        run: |
          wget -O /tmp/bundletool.jar https://github.com/google/bundletool/releases/download/1.15.6/bundletool-all-1.15.6.jar
          filePath=$(ls ${{ env.OUTPUT_DIR }}/*.aab | head -n 1)
          versionName=$(java -jar /tmp/bundletool.jar dump manifest --bundle $filePath --xpath /manifest/@android:versionName)
          echo "versionName=$versionName" >> $GITHUB_ENV
          echo "filePath=$filePath" >> $GITHUB_ENV
      - name: 发布版本
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.apk.outputs.versionName }}
          files: |
            ${{ env.filePath }}